# Generated by Django 4.0.3 on 2022-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='1204', max_length=10),
            preserve_default=False,
        ),
    ]
