# Generated by Django 4.0.3 on 2022-03-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220315_1425'),
        ('store', 'final'),
    ]

    operations = [
    ]
