# Generated by Django 4.0.3 on 2022-03-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
    ]
