# Generated by Django 4.0.3 on 2022-03-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
